language: node_js

node_js:
  - "0.11.13"
  - "0.10"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli

script:
  - grunt travis

env:
  global:
    - secure: Wqeh70b7isp3jDRU3BirQW+ze3JUBbkz99OZMA2vHO7wZhfhCALnh8bGzB6aJHYSk73OAGFEl48+TpEvbTmA59H61KJn4EpXaawj27OHuY46bS7avLfOjQzuSU/sTCE8p6PxJ4re2oKz/lCGrDGfne61UM1WJ9WG3PP6018PN+g=
    - secure: EDysbGRwUe/HsGcv7gcdmaTYi6pwCgiSUKr8yoQ0rpY5O37Q1//V3TI4fr6R0lnIqpyBkHJnl3SuXg/ccLCCJmgI5IaeolQwWplOfqu2NRyUYBkdtoqREcOK6XTVcM2bB1uFd6Krw4nwYcwDSfg/4Y8GWenS/fTNEsM25aqnlRU=

addons:
  sauce_connect: true
